name: Buildozer
on: [push, pull_request]

env:
  buildozer_workdir: launcher
  #buildozer_version: git+https://github.com/misl6/buildozer.git@feat/aab-support
  buildozer_version: git+https://github.com/antocuni/buildozer.git@antocuni/aab-support-and-fileprovider

  # buildozer_workdir: Storage-Example
  # buildozer_version: stable

jobs:

  android_debug:
    name: Android (debug)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ${{ env.buildozer_workdir }}
          buildozer_version: ${{ env.buildozer_version }}
          command: buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: ${{ steps.buildozer.outputs.filename }}


  android_release:
    name: Android (release)
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ${{ env.buildozer_workdir }}
          buildozer_version: ${{ env.buildozer_version }}
          command: buildozer --profile aab android release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ${{ steps.buildozer.outputs.filename }}
