name: Build
on: [push, pull_request]

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: dschep/install-pipenv-action@v1
    - name: Update requirements
      run: |
          python -m pip install --upgrade pip
          pip install pipenv-to-requirements
          pipenv lock
          pipenv_to_requirements

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
          command: buildozer android debug
          workdir: src
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
