name: Android APK  # Name
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android  # Name
    runs-on: ubuntu-latest  # OS

    steps:
      - name: Actions Checkout  # Step 1
        uses: actions/checkout@v2
        with:
          path: master  # /home/runner/work/Android-APP/Android-APP/master
      - name: Setup Python  # Step 2
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # 3.6 or 3.7
      - name: Upgrade Pip  # Step 3
        run: |
          python3 -m pip install --upgrade pip
      - name: Install Cython 
        run: |
          pip3 install --user --upgrade Cython==0.29.19 virtualenv
      - name: Export Android APK file
        run: |
          export PATH=$PATH:~/.local/bin/
      - name: Install buildozer
        run: |
          pip install buildozer
      - name: Install necessary system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev
      - name: Install gstreamer for audio, video (optional)
        run: |
          sudo apt-get install -y \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good
      - name: Init Buildozer
        run: |
          cd ./master/src
          buildozer init
      - name: Make APK
        run: |
          buildozer -v android debug          

