name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip
          pip install pipenv-to-requirements
          pipenv lock
          pipenv_to_requirements
          
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          workdir: src
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-APK@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
