name: Android APK  # Name
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android  # Name
    runs-on: ubuntu-latest  # OS

    steps:
      - name: Actions Checkout  # Step 1
        uses: actions/checkout@v2
        with:
          path: master  # /home/runner/work/Android-APP/Android-APP/master
      - name: Setup Python  # Step 2
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # 3.6 or 3.7
      - name: Upgrade Pip  # Step 3
        run: |
          python3 -m pip install --upgrade pip
      - name: Install Cython 
        run: |
          pip3 install --user --upgrade Cython==0.29.19 virtualenv
      - name: Export Android APK file
        run: |
          export PATH=$PATH:~/.local/bin/
